languageCode = "en"
languageName = "English"
weight = 1
title = "0x0D"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo.png"
  description = "A cyber security enthusiast."

[params.author]
  name = "0x0D"
  email = "coming@soon"
  image = "img/logo.png"
  headline = "A cyber security enthusiast."
  bio = "A cyber security enthusiast."
  links = [
    { github = "https://github.com/0x0Dx" },
  ]
